spring:
  application:
    name: spring-cloud-provider
dubbo:
  application:
    logger: slf4j
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://zk-0.zk-hs.default.svc.cluster.local:2181
  monitor:
    skip: true
#  scan:
#    base-packages: io.github.candyleer.springdubboprovider
management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
jaeger:
  agent:
    host: jaeger-agent
    sampler:
      ratio: 1
