spring:
  application:
    name: spring-dubbo-consumer
dubbo:
  registry:
    address: zookeeper://zk-0.zk-hs.default.svc.cluster.local:2181
  monitor:
    skip: false
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
jaeger:
  agent:
    host: jaeger-agent
  sampler:
    ratio: 1
